### ISSUE TITLE
Proper plugin name

### ISSUE THREAD

**Issue by MichaelsJP** [GIScience/ohsome-qgis-plugin#10]
At the moment the name isn't very `awesome`... Ba dum tss. :grin:   

@TheGreatRefrigerator mentioned to name it accordingly to the ORS qgis plugin `ORSTools`.

Input needed ;)

**Comment by TheGreatRefrigerator** [comment]
I was cleaning up the ORSTools (or ORStools -.-) plugin and did quite some QGIS cookbook reading:
https://docs.qgis.org/3.16/en/docs/pyqgis_developer_cookbook/plugins/releasing.html?highlight=releasing#releasing-your-plugin
I still had the "No plugin in name" in the back of my head, that's why mentioned this.

There are some good and important points. Maybe just give them a quick check as well :)
(e.g. not uploading `__pycache__` in the final plugin data on https://plugins.qgis.org/plugins once you are at that point.
[Here](https://raw.githubusercontent.com/GIScience/orstools-qgis-plugin/main/CHANGELOG.md) are the release instructions for the ORStools plugin if you are interested)

**Comment by joker234** [comment]
we agreed on **ohsomeTools**
